import{i as a,S as c}from"./assets/vendor-46aac873.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const l of r.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&o(l)}).observe(document,{childList:!0,subtree:!0});function n(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerpolicy&&(r.referrerPolicy=e.referrerpolicy),e.crossorigin==="use-credentials"?r.credentials="include":e.crossorigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function o(e){if(e.ep)return;e.ep=!0;const r=n(e);fetch(e.href,r)}})();const u="https://pixabay.com",f="api/",m="41917701-79d925887e26991e7dbaf3a79",i=document.querySelector(".gallery-form");i.addEventListener("submit",function(s){s.preventDefault();const{name:t}=i.elements,n=t.value.trim(),o=document.querySelector(".loader");o.style.display="block",n?t.value.length<3&&alert("Search string must be not less then 3 symbols."):alert("Please fill search string before submitting."),d(n).then(e=>{o.style.display="none",e.hits&&e.hits.length>0?y(e.hits):a.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!"})}).catch(e=>{console.error("Error fetching images:",e)}).finally(()=>i.reset())});function d(s){const t=encodeURIComponent(s),n=`${u}/${f}?key=${m}&q=${t}&image_type=photo&orientation=horizontal&safesearch=true`;return fetch(n).then(o=>{if(!o.ok)throw new Error(o.statusText);return o.json()})}function y(s){const t=document.querySelector(".gallery");t.innerHTML="";const n=s.map(e=>`<li class="gallery-item">
      <a class="gallery-link" href="${e.largeImageURL}">
        <img class="gallery-image" src="${e.webformatURL}" alt="${e.tags}" />
      </a>
    <p>Likes: ${e.likes}</p>
    <p>Views: ${e.views}</p>
    <p>Comments: ${e.comments}</p>
    <p>Downloads: ${e.downloads}</p>
    </li>`).join("");t.innerHTML=n,new c(".gallery a",{animationSpeed:250,captionsData:"alt",captionDelay:250}).refresh()}
//# sourceMappingURL=commonHelpers.js.map
